# This is the configuration file for Ghostty.
# reference: https://ghostty.org/docs/config/reference

# default terminal
term = xterm-256color

# Schrift
font-family = JetBrains Mono Nerdfont Mono
#font-family = CascaydiaCove NF Mono
font-size = 14

# Theme
theme = catppuccin macchiato

# Shell
#command = /usr/bin/zsh

# Transparenz
background-opacity = 0.95

# Cursor
cursor-style = block
cursor-style-blink = true

# Mouse
mouse-hide-while-typing = true

# copy on select
copy-on-select = clipboard

keybind = alt+backspace=text:\x1b\x7f
